CREATE TABLE [apietl].[silverpop_exportList_0]
(
[ETL__silverpop_exportList_id] [uniqueidentifier] NOT NULL,
[ETL__session_id] [uniqueidentifier] NOT NULL,
[ETL__insert_datetime] [datetime] NOT NULL CONSTRAINT [DF__silverpop__ETL____50D0E6F9] DEFAULT (getutcdate()),
[ETL__multi_query_value_for_audit] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RECIPIENT_ID] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Email] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Opt In Date] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Opted Out] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Opt In Details] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Email Type] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Opted Out Date] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Opt Out Details] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ACH Last 4 Digits] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Account Name] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Date of Birth] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EI_Average read time] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EI_Common city] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EI_Common country] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EI_Common device] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EI_Common region] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EI_Engagement category] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EI_Recent city] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EI_Recent country] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EI_Recent region] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[First Name] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GJ Child Count] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Game Rewind Access Code] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Gameday Guide Category] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GenJets Child 1 Birth Month] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GenJets Child 1 First Name] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GenJets Child 2 Birth Month] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GenJets Child 2 First Name] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GenJets Child 3 Birth Month] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GenJets Child 3 First Name] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GenJets Child 4 Birth Month] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GenJets Child 4 First Name] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GenJets Child 5 Birth Month] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GenJets Child 5 First Name] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Groups Game Preference] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Invoice Installment Amont] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Last Name] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PURL] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Payment Method] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Pref_Global_Subscriber] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reward Pick Up Date] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Rewards Points] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STH Account Owner Email] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STH Account Owner Name] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STH Account Owner Phone] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STH Archtics Account number] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STH City] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STH Contact Flag] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STH Full Name] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STH PSL Count] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STH Phone Number] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STH Primary STH Price Level] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STH SEAT TYPE] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STH Shipment Tracking Number] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STH State] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STH Street 1] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STH Street 2] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STH Unsigned Contract PIN] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STH Zip] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STH_Payment_Plan_Amount] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Segment] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Send Hour] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Silverpop_LastClick] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Silverpop_LastOpen] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Silverpop_LastSent] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Special Comments] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Suites Full Name] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Suites Passport Expiration Date] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Suites Passport Number] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Survey Checklist 1] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Survey Checklist 3] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Survey Checklist 4] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Survey Date 3] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Survey Dropdown 2] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Survey Dropdown 3] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Survey Dropdown 4] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Survey Dropdown 5] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Survey Dropdown 6] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Survey Phone number] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Survey Rating 2] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Survey Rating 3] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Survey Rating 4] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Survey Segment] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Survey Text 2] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Survey Text 3] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Survey Text 4] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Survey Text 5] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Survey Text Field] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Survey Textbox 2] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Survey email] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Survey_3GMFLEX_Email] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Survey_3GMFLEX_First_Name] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Survey_3GMFLEX_Game_Selection] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Survey_3GMFLEX_Last_Name] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Survey_3GMFLEX_Num_Tix] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Survey_3GMFLEX_Phone] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Survey_Attendanotherevent] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Survey_Checklist] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Survey_IG_Email] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Survey_IG_First_Name] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Survey_IG_Game_Selection] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Survey_IG_Last_Name] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Survey_IG_Num_Tix] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Survey_IG_Phone] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Survey_OpenEnded] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Survey_Rating] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Test SPAM alert_Behavior] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Test SPAM alert_Rank] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Test SPAM alert_Score] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Total Invoice Amount] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[sub_enews] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[sub_gamedayinfo] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[sub_jetsrewards] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[sub_presales] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[sub_specialeventinvites] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[sub_specialoffers] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[sub_sthservice] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[sub_surveyrequest] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[variable_1] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
GO
ALTER TABLE [apietl].[silverpop_exportList_0] ADD CONSTRAINT [PK__silverpo__0EAED44433D683FA] PRIMARY KEY CLUSTERED  ([ETL__silverpop_exportList_id])
GO
