CREATE TABLE [dbo].[AUDIT20170606seatssold]
(
[event_name] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[section_name] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[row_name] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[seat_num] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[last_seat] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[num_seats] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[acct_id] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[owner_name] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[zip] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[add_datetime] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[price_code] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[promo_code] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[paid] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[printed] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[mobile] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[group_flag] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[consignment] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[comp] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[comp_name] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[purchase_price] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[block_purchase_price] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[full_price] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[block_full_price] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[percent_paid] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[paid_amount] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[acct_rep_id] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[acct_rep_full_name] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ticket_status] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[assoc_acct_id] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[inet_purchase_price] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[acct_type_desc] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ticket_type] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ticket_type_category] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[add_usr] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ledger_code] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[plan_event_name] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[seat_holder_name] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[retail_ticket_type] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[retail_qualifiers] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[retail_price_level] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[sub_plan_event_name] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
GO
